[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
ctf = "4TaboyQDfz6ds2qZpCttzZAHzF7i8qNsFYeoBHTUPvzX"

[programs.devnet]
ctf = "4TaboyQDfz6ds2qZpCttzZAHzF7i8qNsFYeoBHTUPvzX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/icarus/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
